import random
import numpy as np

a=np.array([1,2,3])
print('1D array:')
print(a)
print()
b=np.array([(1,2,3),(4,5,6)])
print('2D array:')
print(b)
print()

print("SOLO UNOS")
unos =np.ones((5,4))
print(unos)
print()
print("RANDOM")
aleatorio=np.random.random((3,4))
print(aleatorio)
print()
print("EMPTY")
vacia=np.empty((3,2))
print(vacia)
print()
print("FULL")
full=np.full((3,2),9)
print(full)
print()
print("IDENTIDAD")
identidad=np.identity(3)
print(identidad)
print()
